blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/heltonteixeira/react-boilerplate/issues
    about: Please use our issue tracker for questions and discussions

  - name: Feature Requests
    url: https://github.com/heltonteixeira/react-boilerplate/issues/new?template=feature_request.yml
    about: Suggest an idea or enhancement for this project

  - name: Bug Reports
    url: https://github.com/heltonteixeira/react-boilerplate/issues/new?template=bug_report.yml
    about: Report a bug to help us improve
