name: Feature Request
description: Suggest an idea for this project
title: '[FEATURE]: '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature for our project!

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Provide a clear and detailed description of the feature you're proposing
      placeholder: As a [user type], I want to [feature] so that [benefit]
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Describe the problem.
      placeholder: I'm always frustrated when [current situation]
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: Explain your proposed technical implementation or design
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request
    validations:
      required: false
